[package]
name    = "aeon"
version = "0.0.1"
authors = ["Yorick Peterse <yorickpeterse@gmail.com>"]

[lib]
name    = "libaeon"
doctest = false

[[bin]]
name = "aeonvm"
test = false

[[bin]]
name = "aeon-bench-gc"
test = false

[dependencies]
getopts = "0.2"
num_cpus = "0.2"
time = "0.1"
crossbeam = "0.2"
